I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/michaelmariannequest.rpy", line 891, in script
    $ marianne_questjustfinished = Trues
  File "game/michaelmariannequest.rpy", line 891, in <module>
    $ marianne_questjustfinished = Trues
NameError: name 'Trues' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/michaelmariannequest.rpy", line 891, in script
    $ marianne_questjustfinished = Trues
  File "C:\Users\Owner\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Owner\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/michaelmariannequest.rpy", line 891, in <module>
    $ marianne_questjustfinished = Trues
NameError: name 'Trues' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
The House On Limbo Lane 1.0
Thu Sep 28 22:05:46 2023
