I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 61, in script
    $config.keymap['game_menu'].remove('mouseup_2')
  File "game/script.rpy", line 61, in <module>
    $config.keymap['game_menu'].remove('mouseup_2')
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 61, in script
    $config.keymap['game_menu'].remove('mouseup_2')
  File "D:\Ren'Py\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Ren'Py\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 61, in <module>
    $config.keymap['game_menu'].remove('mouseup_2')
  File "D:\Ren'Py\renpy-8.0.3-sdk\renpy\revertable.py", line 97, in do_mutation
    return method(self, *args, **kwargs)
ValueError: list.remove(x): x not in list

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
The House On Limbo Lane 1.0
Sun Oct  1 21:38:34 2023
